




E-health-command-response (X.1080.1:10/2011)


-- Module E-health-command-response (X.1080.1:10/2011)
-- See also ITU-T X.1080.1 (10/2011)
-- See also the index of all ASN.1 assignments needed in this document

E-health-command-response {joint-iso-itu-t(2) telebiometrics(42)
  e-health-protocol(3) modules(0) command-response(3) version1(1)} 
  "/Telebiometrics/E-Health_Protocol/Modules/Command-response/Version1"
  DEFINITIONS
AUTOMATIC TAGS ::=
BEGIN

IMPORTS
  EncryptionOptions, IntegrityOptions
    FROM E-health-setup {joint-iso-itu-t(2) telebiometrics(42)
      e-health-protocol(3) modules(0) set-up(1) version1(1)};

-- Type and CLASS definitions for CR interactive message sequences
CR-SEQUENCE ::= CLASS {
  &amp;id                              OBJECT IDENTIFIER UNIQUE,
  &amp;requirements                    ENUMERATED {none, with-2-way-voice,
                                                   with-reverse-video-and-2-way-voice,
                                                   with-2-way-video-and-voice},
  &amp;voice-options                   OBJECT IDENTIFIER,
  &amp;video-options                   OBJECT IDENTIFIER,
  &amp;message-sequence-specification  UniversalString,
  &amp;Interactive-Messages            INTERACTIVE-MESSAGE,
  &amp;first                           INTERACTIVE-MESSAGE
}
WITH SYNTAX {
  INTERACTIVE-SESSION IDENTIFIED BY &amp;id
  REQUIRING &amp;requirements
  WITH VOICE OPTIONS &amp;voice-options
  AND VIDEO OPTIONS &amp;video-options
  SPECIFIED BY &amp;message-sequence-specification
  USING &amp;Interactive-Messages
  BEGINNING WITH &amp;first
}

CR-Sequences CR-SEQUENCE ::=
  {...}

INTERACTIVE-MESSAGE ::= CLASS {
  &amp;id                 INTEGER(0..MAX) UNIQUE,
  &amp;direction          ENUMERATED {command, response},
  &amp;Type               ,
  &amp;expected-response  INTERACTIVE-MESSAGE OPTIONAL,
  -- only for a command
  &amp;next               SEQUENCE OF INTERACTIVE-MESSAGE.&amp;id OPTIONAL
}
WITH SYNTAX {
  STEP &amp;id
  DIRECTION &amp;direction
  USING &amp;Type
  [RESPONSE &amp;expected-response]
  [FOLLOWED BY &amp;next]
}

Identified-Command-Response{INTERACTIVE-MESSAGE:Messages} ::= CHOICE {
  command
    SEQUENCE {message-id
                INTERACTIVE-MESSAGE.&amp;id({Messages})
                  (CONSTRAINED BY {-- direction shall be command -- }),
              message-content
                INTERACTIVE-MESSAGE.&amp;Type({Messages}{@.message-id})
  },
  response
    SEQUENCE {message-id
                INTERACTIVE-MESSAGE.&amp;id({Messages})
                  (CONSTRAINED BY {-- id shall be equal to ---- expected-response of the command -- 
                     }),
              message-content
                INTERACTIVE-MESSAGE.&amp;Type({Messages}{@.message-id})
  }
}

Command-Response ::= SEQUENCE {
  encryptionOptions  EncryptionOptions,
  integrityOptions   IntegrityOptions,
  content
    OCTET STRING
      (CONSTRAINED BY {-- encoding of an Identified-Command-Response value by the current ---- encoding rules followed by an encryption operation if --
         
         -- encryptionOptions is TRUE -- })
}

END

-- Generated by Asnp, the ASN.1 pretty-printer of France Telecom R&amp;D

