




E-health-quantities-and-units (X.1080.1:10/2011)


-- Module E-health-quantities-and-units (X.1080.1:10/2011)
-- See also ITU-T X.1080.1 (10/2011)
-- See also the index of all ASN.1 assignments needed in this document

E-health-quantities-and-units {joint-iso-itu-t(2) telebiometrics(42)
  e-health-protocol(3) modules(0) quantity-and-units(4) version1(1)}
  "/Telebiometrics/E_health_Protocol/Modules/Quantities_And_Units/Version1"
DEFINITIONS AUTOMATIC TAGS ::=
BEGIN

SYMBOLS ::= CLASS {
  &amp;String            UniversalString,
  &amp;attributes        StringAttributes OPTIONAL,
  &amp;id                OBJECT IDENTIFIER UNIQUE,
  &amp;relative-oid-iri  RELATIVE-OID-IRI
}
WITH SYNTAX {
  &amp;String
  [WITH ATTRIBUTES &amp;attributes]
  IDENTIFIED BY &amp;id
  AND &amp;relative-oid-iri
}

StringAttributes ::= BIT STRING {italic(0), betweenParenthesis(1)}

UNIT ::= CLASS {
  &amp;name              PrintableString,
  &amp;symbols           SYMBOLS,
  &amp;id                OBJECT IDENTIFIER UNIQUE,
  &amp;relative-oid-iri  RELATIVE-OID-IRI,
  &amp;Units1            UNIT OPTIONAL,
  &amp;Units2            UNIT OPTIONAL,
  &amp;multipleBaseUnit  UNIT OPTIONAL,
  &amp;multipleFactor    REAL
                           (WITH COMPONENTS {
                              ...,
                              mantissa  (1),
                              base      (10)
                            }) OPTIONAL
}
WITH SYNTAX {
  &amp;name
  USING SYMBOLS &amp;symbols
  IDENTIFIED BY &amp;id
  AND &amp;relative-oid-iri
  [DERIVED BY
   [PRODUCT OF &amp;Units1]
   [DIVIDED BY &amp;Units2]]
  [MULTIPLE OF &amp;multipleBaseUnit
   WITH FACTOR &amp;multipleFactor]
}

QUANTITY ::= CLASS {
  &amp;name              PrintableString,
  &amp;frenchName        UniversalString OPTIONAL,
  &amp;symbols           SYMBOLS,
  &amp;Units             UNIT,
  &amp;Modalities        OBJECT IDENTIFIER,
  &amp;direction         ENUMERATED {in, out} OPTIONAL,
  &amp;id                OBJECT IDENTIFIER UNIQUE,
  &amp;relative-oid-iri  RELATIVE-OID-IRI
}
WITH SYNTAX {
  &amp;name
  [FRENCH &amp;frenchName]
  USING SYMBOLS &amp;symbols
  MEASURED IN &amp;Units
  FOR MODALITIES &amp;Modalities
  [DIRECTION &amp;direction]
  IDENTIFIED BY &amp;id
  AND &amp;relative-oid-iri
}

END

-- Generated by Asnp, the ASN.1 pretty-printer of France Telecom R&amp;D

