



IN-CS3-SCF-SRF-classes (Q.1238.3:06/2000)


-- Module IN-CS3-SCF-SRF-classes (Q.1238.3:06/2000)
-- See also ITU-T Q.1238.3 (06/2000)
-- See also the index of all ASN.1 assignments needed in this document

IN-CS3-SCF-SRF-classes {itu-t recommendation q 1238 modules(1)
  in-cs3-scf-srf-classes(11) version1(0)} DEFINITIONS ::=
BEGIN

IMPORTS
  id-package-emptyConnection, id-rosObject-srf, id-rosObject-ssf,
    ros-InformationObjects, ros-UsefulDefinitions, scf-srf-Protocol,
    scf-srf-datatypes, ssf-scf-datatypes
    FROM IN-CS3-object-identifiers {itu-t recommendation q 1238 modules(1)
      in-cs3-object-identifiers(0) version1(0)}
  ROS-OBJECT-CLASS, CONTRACT, OPERATION-PACKAGE, Code, OPERATION,
    CONNECTION-PACKAGE
    FROM Remote-Operations-Information-Objects {joint-iso-itu-t
      remote-operations(4) informationObjects(5) version1(0)}
  emptyBind, emptyUnbind
    FROM Remote-Operations-Useful-Definitions {joint-iso-itu-t
      remote-operations(4) useful-definitions(7) version1(0)};

UISCRIPT ::= CLASS {
  &amp;SpecificInfo  OPTIONAL,
  &amp;Result        OPTIONAL,
  &amp;id            Code
}
WITH SYNTAX {
  [WITH-SPECIFICINFO &amp;SpecificInfo]
  [WITH-RESULT &amp;Result]
  IDENTIFIED BY &amp;id
}

-- SpecificInfo is used for ScriptRun and ScriptInformation and ScriptClose
--Result is used for ScritEvent 
firstScript UISCRIPT ::= {IDENTIFIED BY  local:1
}

-- firstScript is just an example.
SupportedUIScripts UISCRIPT ::=
  {firstScript, ...
  --full set of User Interaction script 
  }

-- SupportedUIScripts is the full set of User Interaction scripts.
SCF-SRF-BOUNDS ::= CLASS {
  &amp;minAttributesLength           INTEGER OPTIONAL,
  &amp;maxAttributesLength           INTEGER OPTIONAL,
  &amp;minMailBoxIDLength            INTEGER OPTIONAL,
  &amp;maxMailBoxIDLength            INTEGER OPTIONAL,
  &amp;minMessageContentLength       INTEGER OPTIONAL,
  &amp;maxMessageContentLength       INTEGER OPTIONAL,
  &amp;minReceivedInformationLength  INTEGER OPTIONAL,
  &amp;maxReceivedInformationLength  INTEGER OPTIONAL,
  &amp;maxRecordingTime              INTEGER OPTIONAL,
  &amp;numOfMessageIDs               INTEGER OPTIONAL,
  &amp;maxRecordedMessageUnits       INTEGER OPTIONAL,
  &amp;maxVariableParts              INTEGER OPTIONAL
}
WITH SYNTAX {
  [MINIMUM-FOR-ATTRIBUTES &amp;minAttributesLength]
  [MAXIMUM-FOR-ATTRIBUTES &amp;maxAttributesLength]
  [MINIMUM-FOR-MAIL-BOX-ID &amp;minMailBoxIDLength]
  [MAXIMUM-FOR-MAIL-BOX-ID &amp;maxMailBoxIDLength]
  [MINIMUM-FOR-MESSAGE-CONTENT &amp;minMessageContentLength]
  [MAXIMUM-FOR-MESSAGE-CONTENT &amp;maxMessageContentLength]
  [MINIMUM-FOR-RECEIVED-INFORMATION &amp;minReceivedInformationLength]
  [MAXIMUM-FOR-RECEIVED-INFORMATION &amp;maxReceivedInformationLength]
  [MAXIMUM-FOR-RECORDING-TIME &amp;maxRecordingTime]
  [NUM-OF-MESSAGE-IDS &amp;numOfMessageIDs]
  [MAXIMUM-FOR-RECORDED-MESSAGE-UNITS &amp;maxRecordedMessageUnits]
  [NUM-OF-VARIABLE-PARTS &amp;maxVariableParts]
}

-- The following instance of the parameter bound is just an example
networkSpecificSCFSRFBoundSet SCF-SRF-BOUNDS ::= {
  MINIMUM-FOR-ATTRIBUTES              1
  MAXIMUM-FOR-ATTRIBUTES              5
  MINIMUM-FOR-MAIL-BOX-ID             1
  MAXIMUM-FOR-MAIL-BOX-ID             5
  MINIMUM-FOR-MESSAGE-CONTENT         1
  MAXIMUM-FOR-MESSAGE-CONTENT         5
  MINIMUM-FOR-RECEIVED-INFORMATION    1
  MAXIMUM-FOR-RECEIVED-INFORMATION    5
  MAXIMUM-FOR-RECORDING-TIME          5
  NUM-OF-MESSAGE-IDS                  2
  MAXIMUM-FOR-RECORDED-MESSAGE-UNITS  5
  NUM-OF-VARIABLE-PARTS               5 -- must be 5 or

-- greater.
}

END

-- Generated by Asnp, the ASN.1 pretty-printer of France Telecom R&amp;D

